/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mainSidebar: [
    {
      type: 'doc',
      id: 'main', // document ID
      label: '帮助文档', // sidebar label
    },
    {
      type: 'link',
      label: '文档: Aurora Star Laucnher', 
      href: './docs/asl', 
    },
    {
      type: 'link',
      label: '文档: MPI', 
      href: './docs/mpi', 
    },
  ],
  aslSidebar:[
    {
      type: 'doc',
      id: 'asl/asl',
      label: 'Aurora Star Launcher', 
    },
    {
      type: 'doc',
      id: 'asl/introduction/aslIntroduction',
      label: '介绍', 
    },
  ],
};

export default sidebars;
